version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: testcoldmoon
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testcoldmoon
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "32770:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Database=testcoldmoon;Username=testcoldmoon;Password=testpassword"
    depends_on:
      - db

  pgweb:
    image: sosedoff/pgweb
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: "postgres://testcoldmoon:testpassword@db:5432/testcoldmoon?sslmode=disable"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

volumes:
  pgdata: